name: "CLA Signature Bot"
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened,closed,synchronize]

jobs:
  CLABot:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Signature Bot"
        uses: roblox/cla-assistant@2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.CODE_MAID_PAT }}
        with:
          path-to-signatures: 'signatures/version1/cla.json'
          url-to-cladocument: 'https://github.com/0xF6/x3e-simulator/blob/master/LICENSE'
          # This branch can't have protections, commits are made directly to the specified branch.
          branch: 'master'
          blockchain-storage-flag: false
